version: '3'

services:
  cnc-dashboard:
    build: .
    container_name: cnc-dashboard
    ports:
      - "8000:8000"  # Changed to FastAPI's default port
    devices:
      - "/dev/video0:/dev/video0"  # Mount the camera device
      - "/dev/video1:/dev/video1"  # Additional camera device
      - "/dev/video2:/dev/video2"  # Additional camera device
      - "/dev/video3:/dev/video3"  # Additional camera device
    volumes:
      - .:/app  # Mount the current directory for development
      - ./data:/data  # Persistent data storage
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - PYTHONUNBUFFERED=1  # Ensure Python output is sent straight to terminal
      - DATABASE_PATH=data/machine_states.db # Set database path
      - HOST=0.0.0.0  # Explicitly set host to bind to all interfaces
    command: uvicorn app:app --host 0.0.0.0 --port 8000  # Added command to run FastAPI
    user: "1000:1000"
    group_add:
      - 44
    restart: unless-stopped
    privileged: true  # Required for camera access
    networks:
      - cnc-network

networks:
  cnc-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16 